modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits=".siann & kolja_ on discord, this mod uses immersive portals mod as a library"
authors="${mod_authors}"
description='''${mod_description}'''
[[mixins]]
config = "mixins.crazyae2addonslite.json"
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId = "ae2"
    mandatory = true
    versionRange = "[15.3.3,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId="ae2wtlib"
    mandatory=true
    versionRange="[15.2.0,)"
    ordering="AFTER"
    side="BOTH"
